apiVersion: v1
kind: Service
metadata:
  name: devops-mini-service
spec:
  type: NodePort
  selector:
    app: devops-mini
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
